apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-app
  template:
    metadata:
      labels:
        app: tm-app
    spec:
      containers:
        - image: task-management:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: tm-app
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: tm-db-config
                  key: db_url
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: HAZELCAST_NETWORK_JOIN_KUBERNETES_ENABLED
              value: "true"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 8080
            - containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: tm-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      name: tm-app-app
    - port: 5701
      name: tm-app-hazelcast
  selector:
    app: tm-app