apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-db
  strategy: {}
  template:
    metadata:
      labels:
        app: tm-db
    spec:
      containers:
        - image: postgres:alpine
          name: tm-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: tm-db-config
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tm-db-config
                  key: db_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: tm1
          ports:
            - containerPort: 5432
              name: tm-db
      volumes:
        - name: tm-db-storage
          persistentVolumeClaim:
            claimName: tm-db-pvclaim
---
apiVersion: v1
kind: Service
metadata:
  name: tm-db-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: tm-db